modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="secretroomsmod"
version="${file.jarVersion}"
displayName="Secret Rooms 6"
logoFile="secretrooms.png"
authors="Wyn Price"
credits="Originally made by AbrarSyed, continued for 1.12+ by Wyn Price"
description='''This mod adds a variety of cool blocks that camouflage themselves to the surrounding world.
All of these blocks have extremely useful functions that allow you to simply hide your diamonds, or punish all who dare try to get to them.
Hidden doors, pressure plates, hidden levers and more!
'''
